import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import { Loader2, Plus, Edit, Trash2, Eye, FileText, ArrowLeft, Globe, Lock, CheckCircle2, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { CmsPage, CmsPageInput } from '@/types/cms';
import CmsEditor from './CmsEditor';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:4001/api';

type ViewMode = 'list' | 'create' | 'edit';

export default function CmsPagesTab() {
  const [pages, setPages] = useState<CmsPage[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>('list');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  // Form state
  const [slug, setSlug] = useState('');
  const [title, setTitle] = useState('');
  const [contentHtml, setContentHtml] = useState('');
  const [status, setStatus] = useState<'draft' | 'published'>('draft');

  // Delete confirm
  const [deleteTarget, setDeleteTarget] = useState<CmsPage | null>(null);
  const [deleting, setDeleting] = useState(false);

  // AI generation
  const [aiGenerating, setAiGenerating] = useState(false);
  const [aiDescription, setAiDescription] = useState('');
  const [editorKey, setEditorKey] = useState(0);

  const fetchPages = useCallback(async () => {
    setLoading(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;
      const res = await fetch(`${API_BASE}/admin/pages`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      if (!res.ok) throw new Error('Failed to fetch');
      const json = await res.json();
      setPages(json.data || []);
    } catch {
      toast.error('Failed to load pages');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchPages(); }, [fetchPages]);

  const resetForm = () => {
    setSlug('');
    setTitle('');
    setContentHtml('');
    setStatus('draft');
    setEditingId(null);
  };

  const startCreate = () => {
    resetForm();
    setViewMode('create');
  };

  const startEdit = (page: CmsPage) => {
    setSlug(page.slug);
    setTitle(page.title);
    setContentHtml(page.content_html);
    setStatus(page.status);
    setEditingId(page.id);
    setViewMode('edit');
  };

  const handleAiGenerate = async () => {
    if (!title.trim()) {
      toast.error('Enter a page title first');
      return;
    }
    setAiGenerating(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;
      if (!token) { toast.error('Not authenticated'); return; }

      const res = await fetch(`${API_BASE}/ai`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: 'admin_generate_page', title, description: aiDescription }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'AI generation failed');
      setContentHtml(data.result);
      setEditorKey(k => k + 1);
      toast.success('Content generated by AI');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'AI generation failed');
    } finally {
      setAiGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!slug.trim() || !title.trim()) {
      toast.error('Slug and title are required');
      return;
    }
    if (!/^[a-z0-9-]+$/.test(slug)) {
      toast.error('Slug must be lowercase alphanumeric with hyphens only');
      return;
    }
    setSaving(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;
      if (!token) { toast.error('Not authenticated'); return; }

      const body: CmsPageInput = { slug: slug.trim(), title: title.trim(), content_html: contentHtml, status };

      if (viewMode === 'create') {
        const res = await fetch(`${API_BASE}/admin/pages`, {
          method: 'POST',
          headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        });
        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Failed to create' }));
          throw new Error(err.error || 'Failed to create');
        }
        toast.success('Page created');
      } else {
        const res = await fetch(`${API_BASE}/admin/pages/${editingId}`, {
          method: 'PATCH',
          headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        });
        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Failed to update' }));
          throw new Error(err.error || 'Failed to update');
        }
        toast.success('Page saved');
      }
      resetForm();
      setViewMode('list');
      fetchPages();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to save');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;
      if (!token) { toast.error('Not authenticated'); return; }

      const res = await fetch(`${API_BASE}/admin/pages/${deleteTarget.id}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: 'Failed to delete' }));
        throw new Error(err.error || 'Failed to delete');
      }
      toast.success('Page deleted');
      setDeleteTarget(null);
      fetchPages();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to delete');
    } finally {
      setDeleting(false);
    }
  };

  const handlePublishToggle = async (page: CmsPage) => {
    const newStatus = page.status === 'published' ? 'draft' : 'published';
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const token = session?.access_token;
      if (!token) { toast.error('Not authenticated'); return; }

      const res = await fetch(`${API_BASE}/admin/pages/${page.id}`, {
        method: 'PATCH',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus }),
      });
      if (!res.ok) throw new Error('Failed to update status');
      toast.success(newStatus === 'published' ? 'Page published' : 'Page unpublished');
      fetchPages();
    } catch {
      toast.error('Failed to update status');
    }
  };

  // ── List View ──
  if (viewMode === 'list') {
    return (
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              CMS Pages
            </CardTitle>
            <Button size="sm" onClick={startCreate}><Plus className="w-3.5 h-3.5 mr-1" /> Create Page</Button>
          </div>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-6 h-6 animate-spin text-secondary" />
            </div>
          ) : pages.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <p>No pages yet. Create your first CMS page.</p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Title</TableHead>
                  <TableHead>Slug</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>System</TableHead>
                  <TableHead>Updated</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pages.map((page) => (
                  <TableRow key={page.id}>
                    <TableCell className="font-medium">{page.title}</TableCell>
                    <TableCell className="text-muted-foreground font-mono text-xs">/{page.slug}</TableCell>
                    <TableCell>
                      <Badge variant={page.status === 'published' ? 'default' : 'secondary'}>
                        {page.status === 'published' ? (
                          <><Globe className="w-3 h-3 mr-1" /> Published</>
                        ) : (
                          <><Lock className="w-3 h-3 mr-1" /> Draft</>
                        )}
                      </Badge>
                    </TableCell>
                    <TableCell>{page.is_system ? <Badge variant="outline">System</Badge> : '—'}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">
                      {new Date(page.updated_at).toLocaleDateString()}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button size="sm" variant="ghost" onClick={() => handlePublishToggle(page)} title={page.status === 'published' ? 'Unpublish' : 'Publish'}>
                          {page.status === 'published' ? <Lock className="w-3.5 h-3.5" /> : <CheckCircle2 className="w-3.5 h-3.5" />}
                        </Button>
                        <Button size="sm" variant="ghost" onClick={() => startEdit(page)}>
                          <Edit className="w-3.5 h-3.5" />
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          className="text-red-500"
                          disabled={page.is_system}
                          title={page.is_system ? 'System pages cannot be deleted' : 'Delete'}
                          onClick={() => setDeleteTarget(page)}
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>

        {/* Delete Confirmation */}
        <Dialog open={!!deleteTarget} onOpenChange={() => setDeleteTarget(null)}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Delete Page</DialogTitle>
            </DialogHeader>
            <p className="text-sm text-muted-foreground">
              Are you sure you want to delete <strong>{deleteTarget?.title}</strong>? This action cannot be undone.
            </p>
            {deleteTarget?.is_system && (
              <p className="text-sm text-destructive font-medium">System pages cannot be deleted.</p>
            )}
            <DialogFooter>
              <Button variant="outline" onClick={() => setDeleteTarget(null)} disabled={deleting}>Cancel</Button>
              <Button variant="destructive" onClick={handleDelete} disabled={deleting || deleteTarget?.is_system}>
                {deleting ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : null}
                Delete
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </Card>
    );
  }

  // ── Create / Edit View ──
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button size="sm" variant="ghost" onClick={() => { resetForm(); setViewMode('list'); }}>
              <ArrowLeft className="w-4 h-4 mr-1" /> Back
            </Button>
            <CardTitle>{viewMode === 'create' ? 'Create Page' : 'Edit Page'}</CardTitle>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant={status === 'published' ? 'secondary' : 'default'}
              size="sm"
              onClick={() => setStatus(status === 'published' ? 'draft' : 'published')}
            >
              {status === 'published' ? <Lock className="w-3.5 h-3.5 mr-1" /> : <Globe className="w-3.5 h-3.5 mr-1" />}
              {status === 'published' ? 'Set Draft' : 'Set Published'}
            </Button>
            <Button size="sm" onClick={handleSave} disabled={saving}>
              {saving ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <CheckCircle2 className="w-4 h-4 mr-1" />}
              {saving ? 'Saving...' : 'Save'}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 max-w-3xl">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <Label>Title</Label>
            <Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Page title" />
          </div>
          <div className="space-y-1.5">
            <Label>Slug</Label>
            <Input
              value={slug}
              onChange={(e) => setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-'))}
              placeholder="my-page-slug"
            />
            <p className="text-xs text-muted-foreground">URL: /pages/{slug || 'my-slug'}</p>
          </div>
        </div>

        {/* AI Page Generator */}
        <div className="border border-dashed border-secondary/30 rounded-lg p-4 space-y-3 bg-muted/30">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <Sparkles className="w-4 h-4 text-secondary" />
                AI Page Generator
              </div>
              <span className="text-xs text-muted-foreground">Optional — auto-fills content below</span>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs">Describe what this page should say</Label>
              <Textarea
                value={aiDescription}
                onChange={(e) => setAiDescription(e.target.value)}
                placeholder="e.g. Cover our mission, team background, and key milestones..."
                className="min-h-[60px] text-sm"
              />
            </div>
            <Button
              size="sm"
              variant="secondary"
              onClick={handleAiGenerate}
              disabled={aiGenerating}
              className="w-full sm:w-auto"
            >
              {aiGenerating ? (
                <><Loader2 className="w-3.5 h-3.5 animate-spin mr-1.5" /> Generating...</>
              ) : (
                <><Sparkles className="w-3.5 h-3.5 mr-1.5" /> Generate Content</>
              )}
            </Button>
          </div>

        <div className="space-y-1.5">
          <Label>Content</Label>
          <CmsEditor key={editorKey} content={contentHtml} onChange={setContentHtml} placeholder="Start writing your page content..." />
        </div>
      </CardContent>
    </Card>
  );
}
